# Generated by Django 3.2.4 on 2021-06-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='', max_length=100, verbose_name='권한'),
        ),
    ]
